### ISSUE TITLE
Submissão de palestras para o meetup do dia 28/07

### ISSUE THREAD

**Issue by rayansostenes** [Grupy-GO/meetup-grupy#1]
Votem com um joinha nas palestras que mais te interessarem. Dia 21/07 fecha a votação e as mais bem votadas serão escolhidas até que se preencham os slots de tempo para palestras dentro da programação do meetup.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

**Comment by juuh42dias** [comment]
Juliana Dias && Rayan Sóstenes - `Ruby || Python`

Iremos apresentar um comparativo de alguns métodos mais conhecidos em ambas as linguagens, demonstrando seu uso e comportamento.

**Comment by daniloroddrigues** [comment]
Danilo Silva Rodrigues - Primeiro Deploy Agente nunca Esquece

Faremos uma aplicação simples para web usando Django e o deploy será feito na plataforma
heroku.

**Comment by gabrielrumiranda** [comment]
Gabriel Rubens - Scrapy, fazendo seu primeiro crawler com Python

Faremos uma introdução sobre web crawler, e criaremos um simples crawler

**Comment by jcserracampos** [comment]
Júlio Campos - Blockchain 101 com Python

Blockchain é uma das palavras do momento e nada melhor para entender os conceitos básico do que colocar a mão na massa. Conceitos como transação, blocos e validação por hash serão mostrados com Python.

**Comment by nathanmartins** [comment]
Nathan Martins - Desenvolvimento web com DDD usando Python e Django. 

Breve explicação do que é DDD e qual a utilidade disso no dia a dia, além de uma contextualização histórica de como chegamos até aqui. Além de uma demonstração de como é usado o DDD para guiar o processo de desenvolvimento com Python e Django.
