### ISSUE TITLE
Submissão de palestras para o meetup do dia 15/12

### ISSUE THREAD

**Issue by daniloroddrigues** [Grupy-GO/meetup-grupy#2]
Votem com um joinha nas palestras que mais te interessarem. Dia 15/12 fecha a votação e as mais bem votadas serão escolhidas até que se preencham os slots de tempo para palestras dentro da programação do meetup.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

**Comment by daniloroddrigues** [comment]
Danilo Silva Rodrigues - Primeiro Deploy Agente nunca Esquece

Faremos uma aplicação simples com Python para web usando Django e o deploy será feito na plataforma heroku.

**Comment by talesmgodois** [comment]
Tales Marinho Godois - Redes neurais com Pytorch

Explicarei como funciona uma rede neural simples, apresentarei a plataforma Pytorch e criaremos um modelo para classificar números.
