### ISSUE TITLE
Submissão de palestras para o meetup do dia 26/01/2019

### ISSUE THREAD

**Issue by daniloroddrigues** [Grupy-GO/meetup-grupy#3]
Votem com um joinha nas palestras que mais te interessarem. Dia 26/01/2019 fecha a votação e as mais bem votadas serão escolhidas até que se preencham os slots de tempo para palestras dentro da programação do meetup.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

**Comment by fcevado** [comment]
Flávio "Cevado" - O que é Elixir?
Uma apresenntação simples de Elixir e seu ecossistema, com casos de usos interessantes e live coding demonstrando alguns recursos da plataforma.

**Comment by hugoseabra** [comment]
> Flávio "Cevado" - O que é Elixir?
> Uma apresenntação simples de Elixir e seu ecossistema, com casos de usos interessantes e live coding demonstrando alguns recursos da plataforma.

Além desse conteúdo, tem como apresentar uma aplicação desenvolvida com Elixir, hands-on?

Vamos pensar em um problema simples, para ser desenvolvido com Elixir e Python, com algum framework (Flask, Django, Pyramid, etc.). Que tal?

**Comment by fcevado** [comment]
@hugoseabra rola demais, eu não me arrisco fazer algo em python(mais de 3 anos sem escrever python, não me arrisco tanto assim não) mas se alguém animar fazer a parte de python e eu Elixir, acho que seria uma boa :smile:

**Comment by nathanmartins** [comment]
**Nathan Martins - Como fazer documentação em projetos Python**
Uma introdução básica as principais ferramentas de documentação como _Sphinx_ com hospedagem usando ReadTheDocs, além de uma apresentação/comparação entre o _Swagger_ e _API Blueprint_. Caso dê tempo podemos fazer uma demo de construção de uma API em _Flask_


Opiniões? Sugestões?

**Comment by hugoseabra** [comment]
> @hugoseabra rola demais, eu não me arrisco fazer algo em python(mais de 3 anos sem escrever python, não me arrisco tanto assim não) mas se alguém animar fazer a parte de python e eu Elixir, acho que seria uma boa

Então vamos fazer uma aplicação simples. Que tal uma aplicação que possa demonstrar um CRUD básico para darmos noção de persistência, criação de tela, gerenciamento de dados e comunicação como camada HTTP?

**Comment by daniloroddrigues** [comment]
> > @hugoseabra rola demais, eu não me arrisco fazer algo em python(mais de 3 anos sem escrever python, não me arrisco tanto assim não) mas se alguém animar fazer a parte de python e eu Elixir, acho que seria uma boa
> 
> Então vamos fazer uma aplicação simples. Que tal uma aplicação que possa demonstrar um CRUD básico para darmos noção de persistência, criação de tela, gerenciamento de dados e comunicação como camada HTTP?

seria bacana.
